name: Sync and Deploy
on:
  push:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 */12 * * *' # 每 12 小时运行一次，可调整
jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install Ruby dependencies
        run: |
          gem install bundler:2.5.23
          bundle install
      - name: Clean Jekyll site
        run: bundle exec jekyll clean
      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: jekyll build --trace
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
