name: Sync and Deploy
on:
  push:
  workflow_dispatch: # æ‰‹åŠ¨è§¦å‘
  schedule:
    - cron: '0 */12 * * *' # æ¯ 12 å°æ—¶è¿è¡Œä¸€æ¬¡ï¼Œå¯è°ƒæ•´
jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: pip install requests markdown-it-py pypinyin # ğŸ‘ˆ åœ¨è¿™é‡Œæ·»åŠ  pypinyin
      - name: Sync from Notion
        run: python _scripts/notion_sync.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install Ruby dependencies
        run: |
          gem install bundler:2.5.23
          bundle install
      - name: Build Jekyll site
        run: jekyll build --trace
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
